
version: "3"

services:
  # nginx
  #   Proxy service frontend.
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./Persistent/proxy/certificates:/etc/nginx/certs:ro"

  # nginx-config
  #   Generates the configuration setup for each container managed by the frontend
  #   service in order for the subdomain routing to work correctly.
  nginx-config:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-config
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./Persistent/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  # letsencrypt
  #   Companion service which generates the certificates for each container managed
  #   by the frontend service.
  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./Persistent/proxy/certificates:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-config

  # Services listed below
  # Example 1: www.example.com
  #
  # www-example-com
  #   An example service, in this case a simple Nginx file provider, with its domain
  #   settings and connection to the frontend service.
  www-example-com:
    restart: always
    image: nginx
    container_name: www-example-com
    volumes:
      - "./Persistent/www.example.com/conf.d:/etc/nginx/conf.d:ro"
      - "./Services/www.example.com:/usr/share/nginx/html:ro"
    environment:
      - VIRTUAL_HOST=example.com, www.example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=example.com, www.example.com
      - LETSENCRYPT_EMAIL=letsencrypt@example.com
